minify:
  disableXML: true
  minifyOutput: true
  
params:
  env: production
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  
homeInfoParams:
  Title: "Hi there"
  Content: "Welcome"

socialIcons:
  - name: github
    url: "https://github.com/philam"
